def handleRemoveError(func, path, exc):
    excvalue = exc[1]
    print 'Retrying shutil.rmtree of sandbox (2 sec delay). Will ignore errors. Exception was', excvalue.errno
    time.sleep(2)
    try:
        func(path)
    except OSError:
        pass
