def __test_fail__(self):
    '\n        Failure of attempted row write to db.\n        The row is logged along with a message \n        to the python_message table.\n\n        The row is then filled in with defaults\n        corresponding to a failed test.\n        '
    self.perfdb_connection.db.rollback()
    message = MySQLdb.escape_string('ERROR: Could not write row to table {}.'.format(self.table_name))
    py_table = TableRow('python_message', self.perfdb_connection)
    py_table.row['message'] = message
    py_table.row['row'] = MySQLdb.escape_string(str(self.row))
    py_table.update(True)
    print message
    print 'Some entries were missing and the row could not be written.'
    print "Here's the incomplete row: "
    print self.row
