{
  try {
    join();
  }
 catch (  InterruptedException e) {
    Log.write(e);
  }
}
