def handleRemoveError(func, path, exc):
    excvalue = exc[1]
    print 'Retrying shutil.rmtree of sandbox after 2 secs. Will ignore errors. exception was', excvalue.errno
    time.sleep(2)
    try:
        func(path)
    except OSError:
        pass
